wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718567175
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.9.6
      5: 0.17.1
      8:
      - 5
      13: darwin-x86_64
